events_app/lib/events_app_web/router.ex
defmodule EventsAppWeb.Router do
  use EventsAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsAppWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsAppWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    resources "/sessions", SessionController,
     only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsAppWeb.Telemetry
    end
  end
end

events_app/lib/events_app_web/views/layout_view.ex
defmodule EventsAppWeb.LayoutView do
  use EventsAppWeb, :view
end

events_app/lib/events_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>EventsApp · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <div role="main" class="container">
          <div class="row">
                  <div class="col">
                    <%= link("Events", to: Routes.event_path(@conn, :index)) %>
                  </div>
                  <div class="col">
                     <%= link("Users", to: Routes.user_path(@conn, :index)) %>
                   </div>
                  <%= if @conn.assigns[:current_user] do %>
                    <div class="col">
                      User: <%= @current_user.name %> |
                      <%= link("Logout", to: Routes.session_path(@conn, :delete),
                        method: :delete) %>
                    </div>
                  <% else %>
                    <div class="col">
                      <%= form_for @conn, Routes.session_path(@conn, :create),
                      [class: "form-inline"], fn f -> %>
                        <%= text_input f, :email, class: "form-control" %>
                        <%= submit "Login", class: "btn btn-secondary" %>
                      <% end %>
                    </div>
                    <div class="col my-2">
                      <p><%= link "Register", to: Routes.user_path(@conn, :new) %></p>
                    </div>
                  <% end %>
                </div>
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>

          <%= @inner_content %>
        </div>
  </body>
</html>